# Generated by Django 5.2.5 on 2025-08-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_phone_number'),
        ('core', '0005_user_phone_number_alter_order_status_and_more'),
    ]

    operations = [
    ]
