# Generated by Django 5.2.5 on 2025-10-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('customer', 'Customer'), ('youth_lab', 'Youth Lab'), ('guest', 'Guest')], default='staff', max_length=20),
        ),
    ]
